### PR TITLE
Update index.html

### PR DESCRIPTION
**Pull request by serjan-nasredin**

### CODE REVIEW

**Comment by vifon** [comment]
Looks reasonable, thanks! @toonn, any comments?

**Review by toonn — APPROVED** [review]
Looks cromulent to me. Didn't test though. We're sure we don't generate `index.html` from some markdown file or something, right?

**Comment by vifon** [comment]
I don't think this is the case, and I don't see any other branches it could be generated from by Github Pages. I think it was hand-written by @hut.

**Comment by toonn** [comment]
@snxx-lppxx, thanks for the contribution! 🎉

**Pull request merged**
